algoritmo "semnome"
var   A,B,C,Delta:real

inicio
      Escreval("Sabendo que uma equação do segundo grau é ax² + bx + c = 0 digite seus coeficientes:")
      Escreva("Digite o valor de A: ")
      Leia(A)
      Escreva("Digite o valor de B: ")
      Leia(B)
      Escreva("Digite o valor de C: ")
      Leia(C)
      Delta <-Exp(B,2) - 4*A*C
      Escreva("O valor de Delta é: ",Delta)
fimalgoritmo