algoritmo "semnome"
var
     dist, km, hm, dam,dm, cm, mm:real
inicio
      Escreva("Digite uma distância em metros: ")
      Leia(dist)
      km <- dist/1000
      hm <- dist/100
      dam <- dist/10
      dm <- dist * 10
      cm <- dist * 100
      mm <- dist * 1000
      Escreval(km,"km")
      Escreval(hm,"Hm")
      Escreval(dam,"Dam")
      Escreval(dm,"dm")
      Escreval(cm,"cm")
      Escreva(mm,"mm")
      

fimalgoritmo